version: '3'
services:
  marketplace-db:
    image: 'postgres:13.1-alpine'
    container_name: marketplace
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketplace
