spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
